all: printf scanf getchar

printf: printf.c
	gcc -ansi -Wall -Werror -o printf printf.c

scanf: scanf.c
	gcc -ansi -Wall -Werror -o scanf scanf.c

getchar: getchar.c
	gcc -ansi -Wall -Werror -o getchar getchar.c

clean:
	rm printf scanf getchar *txt *out
