
goal: test_mystring 


test_mystring: test_mystring.c mystring.c
	gcc -Wall -Werror -std=c99 -g -o test_mystring test_mystring.c mystring.c

clean:
	rm -f test_mystring total.txt total.out *.out





